## global properties for all properties
spring:
  application:
    name: properties-samples

---
## used if no profile is set at application startup
spring:
  profiles: default
security:
  user:
    password: no password
server:
  address: localhost
  port: 8080

---
## used if profile dev is set at application startup
## --spring.profiles.active=dev
spring:
  profiles: dev
security:
  user:
    password: weak password
server:
  address: localhost
  port: 8003

---
## used if profile prod is set at application startup
## --spring.profiles.active=prod
spring:
  profiles: prod
security:
  user:
    password: strong password
server:
  address: localhost
  port: 8004